#!/bin/sh
set -e

SUBCOMMAND=""
OUT=""
DRY_RUN=""
NAMESPACE="default"
PROVIDER="github-actions"
DEPLOY=""
STAGES=""
FILES=""

print_help() {
  cat <<'EOF'
skillpack infra-gen — Generate infrastructure configs from plain English

SUBCOMMANDS
  skillpack infra-gen k8s <docker-compose.yml> [--namespace production]
  skillpack infra-gen ci <dir> [--provider github-actions|gitlab|circleci|bitbucket]
  skillpack infra-gen nginx "proxy /api to localhost:3000"
  skillpack infra-gen terraform "AWS: VPC + ECS + RDS + S3"

OPTIONS
  --out <dir>        Output directory
  --namespace <ns>   Kubernetes namespace (default: default)
  --provider <p>     CI provider
  --deploy <desc>    Deployment trigger description
  --stages <list>    Comma-separated CI stages
  --dry-run          Preview output
  --help, -h         Show this help
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --help|-h) print_help; exit 0 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --out) OUT="$2"; shift 2 ;;
    --namespace) NAMESPACE="$2"; shift 2 ;;
    --provider) PROVIDER="$2"; shift 2 ;;
    --deploy) DEPLOY="$2"; shift 2 ;;
    --stages) STAGES="$2"; shift 2 ;;
    -*) echo "Unknown option: $1" >&2; exit 1 ;;
    *)
      if [ -z "$SUBCOMMAND" ]; then
        SUBCOMMAND="$1"
      else
        FILES="$FILES $1"
      fi
      shift
      ;;
  esac
done

generate_k8s() {
  local file="$1"
  
  if ! command -v yq >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
    echo "Error: yq or python3 required for K8s generation" >&2
    echo "  sudo apt install yq  # or: pip3 install yq" >&2
    exit 1
  fi
  
  echo "# Generated by skillpack infra-gen"
  echo "# Namespace: $NAMESPACE"
  echo ""
  
  # Simple docker-compose parser using awk
  awk -v ns="$NAMESPACE" '
    /^services:/ { in_services=1; next }
    /^[a-z]/ { in_services=0 }
    in_services && /^[[:space:]]+[a-z]/ { gsub(/[:[:space:]]/, ""); service=$0; next }
    in_services && /image:/ { gsub(/.*image:[[:space:]]*/, ""); image=$0; 
      print "---"
      print "apiVersion: apps/v1"
      print "kind: Deployment"
      print "metadata:"
      print "  name: " service
      print "  namespace: " ns
      print "  labels:"
      print "    app: " service
      print "spec:"
      print "  replicas: 1"
      print "  selector:"
      print "    matchLabels:"
      print "      app: " service
      print "  template:"
      print "    metadata:"
      print "      labels:"
      print "        app: " service
      print "    spec:"
      print "      containers:"
      print "        - name: " service
      print "          image: " image
      print ""
      print "---"
      print "apiVersion: v1"
      print "kind: Service"
      print "metadata:"
      print "  name: " service
      print "  namespace: " ns
      print "spec:"
      print "  selector:"
      print "    app: " service
      print "  ports:"
      print "    - port: 80"
      print "      targetPort: 80"
      print "  type: ClusterIP"
      print ""
    }
  ' "$file"
}

generate_ci() {
  local provider="$1"
  local stages="${2:-test,build,deploy}"
  
  case "$provider" in
    github-actions)
      cat <<CI
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
$(echo "$stages" | tr ',' '\n' | while read -r stage; do
  echo "  $stage:"
  echo "    runs-on: ubuntu-latest"
  echo "    steps:"
  echo "      - uses: actions/checkout@v4"
  case "$stage" in
    test)
      echo "      - uses: actions/setup-node@v4"
      echo "        with:"
      echo "          node-version: 20"
      echo "      - run: npm ci"
      echo "      - run: npm test"
      ;;
    build)
      echo "      - uses: actions/setup-node@v4"
      echo "        with:"
      echo "          node-version: 20"
      echo "      - run: npm ci"
      echo "      - run: npm run build"
      ;;
    deploy)
      echo "      - run: echo Deploy step"
      ;;
  esac
  echo ""
done)
CI
      ;;
    gitlab)
      cat <<CI
stages:
$(echo "$stages" | tr ',' '\n' | sed 's/^/  - /')

$(echo "$stages" | tr ',' '\n' | while read -r stage; do
  echo "$stage:"
  echo "  stage: $stage"
  echo "  script:"
  case "$stage" in
    test)  echo "    - npm ci && npm test" ;;
    build) echo "    - npm ci && npm run build" ;;
    *)     echo "    - echo Deploy" ;;
  esac
  echo ""
done)
CI
      ;;
    circleci)
      cat <<CI
version: 2.1

jobs:
$(echo "$stages" | tr ',' '\n' | while read -r stage; do
  echo "  $stage:"
  echo "    docker:"
  echo "      - image: cimg/node:20.0"
  echo "    steps:"
  echo "      - checkout"
  case "$stage" in
    test)  echo "      - run: npm ci && npm test" ;;
    build) echo "      - run: npm ci && npm run build" ;;
    *)     echo "      - run: echo Deploy" ;;
  esac
  echo ""
done)

workflows:
  main:
    jobs:
$(echo "$stages" | tr ',' '\n' | sed 's/^/      - /')
CI
      ;;
    bitbucket)
      cat <<CI
pipelines:
  default:
$(echo "$stages" | tr ',' '\n' | while read -r stage; do
  echo "    - step:"
  echo "        name: $stage"
  echo "        image: node:20"
  echo "        script:"
  case "$stage" in
    test)  echo "          - npm ci && npm test" ;;
    build) echo "          - npm run build" ;;
    *)     echo "          - echo Deploy" ;;
  esac
done)
CI
      ;;
  esac
}

generate_nginx() {
  local desc="$1"
  echo "# Generated by skillpack infra-gen"
  echo "# $desc"
  echo ""
  echo "server {"
  echo "    listen 80;"
  echo "    server_name _;"
  echo ""
  
  echo "$desc" | tr ',' '\n' | while read -r rule; do
    case "$rule" in
      *proxy*to*)
        from=$(echo "$rule" | grep -oE 'proxy[[:space:]]+[^[:space:]]+' | awk '{print $2}')
        to=$(echo "$rule" | grep -oE 'to[[:space:]]+[^[:space:]]+' | awk '{print $2}')
        echo "    location $from {"
        echo "        proxy_pass $to;"
        echo "        proxy_set_header Host \$host;"
        echo "        proxy_set_header X-Real-IP \$remote_addr;"
        echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
        echo "    }"
        echo ""
        ;;
      *serve*from*)
        path=$(echo "$rule" | grep -oE 'serve[[:space:]]+[^[:space:]]+' | awk '{print $2}')
        root=$(echo "$rule" | grep -oE 'from[[:space:]]+[^[:space:]]+' | awk '{print $2}')
        echo "    location $path {"
        echo "        root $root;"
        echo "        try_files \$uri \$uri/ =404;"
        echo "    }"
        echo ""
        ;;
    esac
  done
  
  echo "}"
}

generate_terraform() {
  local desc="$1"
  echo "# Generated by skillpack infra-gen"
  echo "# $desc"
  echo ""
  echo 'terraform {'
  echo '  required_providers {'
  echo '    aws = {'
  echo '      source  = "hashicorp/aws"'
  echo '      version = "~> 5.0"'
  echo '    }'
  echo '  }'
  echo '}'
  echo ""
  echo 'provider "aws" {'
  echo '  region = "us-east-1"'
  echo '}'
  echo ""
  
  case "$desc" in
    *VPC*|*vpc*)
      echo 'resource "aws_vpc" "main" {'
      echo '  cidr_block = "10.0.0.0/16"'
      echo '  tags = { Name = "main-vpc" }'
      echo '}'
      echo ""
      ;;
  esac
  
  case "$desc" in
    *ECS*|*ecs*|*cluster*)
      echo 'resource "aws_ecs_cluster" "main" {'
      echo '  name = "main-cluster"'
      echo '}'
      echo ""
      ;;
  esac
  
  case "$desc" in
    *RDS*|*rds*|*postgres*|*database*)
      echo 'resource "aws_db_instance" "main" {'
      echo '  identifier     = "main-db"'
      echo '  engine         = "postgres"'
      echo '  instance_class = "db.t3.micro"'
      echo '  allocated_storage = 20'
      echo '  skip_final_snapshot = true'
      echo '}'
      echo ""
      ;;
  esac
  
  case "$desc" in
    *S3*|*s3*|*bucket*)
      echo 'resource "aws_s3_bucket" "main" {'
      echo '  bucket = "my-app-bucket"'
      echo '  tags = { Name = "Main bucket" }'
      echo '}'
      echo ""
      ;;
  esac
}

case "$SUBCOMMAND" in
  k8s)
    file=$(echo "$FILES" | awk '{print $1}')
    [ -z "$file" ] || [ ! -f "$file" ] && echo "Error: docker-compose file not found." >&2 && exit 1
    output=$(generate_k8s "$file")
    ;;
  ci)
    output=$(generate_ci "$PROVIDER" "$STAGES")
    ;;
  nginx)
    desc=$(echo "$FILES" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
    [ -z "$desc" ] && desc="proxy /api to localhost:3000"
    output=$(generate_nginx "$desc")
    ;;
  terraform)
    desc=$(echo "$FILES" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
    [ -z "$desc" ] && desc="AWS VPC"
    output=$(generate_terraform "$desc")
    ;;
  *)
    [ -z "$SUBCOMMAND" ] && print_help && exit 0
    echo "Error: Unknown subcommand \"$SUBCOMMAND\"" >&2
    exit 1
    ;;
esac

if [ "$DRY_RUN" = "1" ]; then
  echo "[dry-run] Would output:" >&2
  echo "$output"
elif [ -n "$OUT" ]; then
  mkdir -p "$OUT"
  case "$SUBCOMMAND" in
    k8s)       outfile="$OUT/k8s-manifests.yml" ;;
    ci)        outfile="$OUT/$([ "$PROVIDER" = "gitlab" ] && echo ".gitlab-ci.yml" || echo "ci.yml")" ;;
    nginx)     outfile="$OUT/nginx.conf" ;;
    terraform) outfile="$OUT/main.tf" ;;
  esac
  echo "$output" > "$outfile"
  echo "Written to $outfile" >&2
else
  echo "$output"
fi
