#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

function parseArgs(argv) {
  const args = { subcommand: null, files: [], help: false, dryRun: false, out: null, namespace: 'default', provider: 'github-actions', deploy: null, stages: null };
  let i = 0;
  while (i < argv.length) {
    const a = argv[i];
    if (a === '--help' || a === '-h') { args.help = true; }
    else if (a === '--dry-run') { args.dryRun = true; }
    else if (a === '--out') { args.out = argv[++i]; }
    else if (a === '--namespace') { args.namespace = argv[++i]; }
    else if (a === '--provider') { args.provider = argv[++i]; }
    else if (a === '--deploy') { args.deploy = argv[++i]; }
    else if (a === '--stages') { args.stages = argv[++i]; }
    else if (!a.startsWith('-')) {
      if (!args.subcommand) args.subcommand = a;
      else args.files.push(a);
    }
    i++;
  }
  return args;
}

function printHelp() {
  console.log(`
skillpack infra-gen — Generate infrastructure configs from plain English

SUBCOMMANDS
  skillpack infra-gen k8s <docker-compose.yml> [--namespace production] [--out k8s/]
  skillpack infra-gen ci <dir> [--provider github-actions|gitlab|circleci|bitbucket] [--deploy "trigger"]
  skillpack infra-gen nginx "proxy /api to localhost:3000"
  skillpack infra-gen apache "proxy /api to localhost:3000"
  skillpack infra-gen terraform "AWS: VPC + ECS + RDS + S3"

OPTIONS
  --out <dir>        Output directory
  --namespace <ns>   Kubernetes namespace (default: default)
  --provider <p>     CI provider
  --deploy <desc>    Deployment trigger description
  --stages <list>    Comma-separated CI stages
  --dry-run          Preview output
  --help, -h         Show this help
`);
}

function dockerToK8s(composeFile, namespace) {
  const content = fs.readFileSync(composeFile, 'utf-8');
  let compose;
  try {
    compose = yaml.load(content);
  } catch (e) {
    console.error(`Error parsing docker-compose: ${e.message}`);
    process.exit(1);
  }

  const services = compose.services || {};
  const manifests = [];

  for (const [name, svc] of Object.entries(services)) {
    const deployment = {
      apiVersion: 'apps/v1',
      kind: 'Deployment',
      metadata: { name, labels: { app: name } },
      spec: {
        replicas: 1,
        selector: { matchLabels: { app: name } },
        template: {
          metadata: { labels: { app: name } },
          spec: {
            containers: [{
              name,
              image: svc.image || `${name}:latest`,
              ports: svc.ports ? svc.ports.map(p => ({ containerPort: parseInt(String(p).split(':')[0]) })) : [],
              env: svc.environment ? Object.entries(svc.environment).map(([k, v]) => ({ name: k, value: String(v) })) : [],
            }]
          }
        }
      }
    };

    const service = {
      apiVersion: 'v1',
      kind: 'Service',
      metadata: { name },
      spec: {
        selector: { app: name },
        ports: svc.ports ? svc.ports.map(p => ({ port: parseInt(String(p).split(':')[0]), targetPort: parseInt(String(p).split(':')[0]) })) : [],
        type: 'ClusterIP'
      }
    };

    manifests.push({ name, deployment, service });
  }

  let output = `# Generated by skillpack infra-gen\n# Namespace: ${namespace}\n\n`;
  for (const m of manifests) {
    output += `---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ${m.deployment.metadata.name}\n  namespace: ${namespace}\n  labels:\n    app: ${m.deployment.metadata.name}\nspec:\n  replicas: ${m.deployment.spec.replicas}\n  selector:\n    matchLabels:\n      app: ${m.deployment.metadata.name}\n  template:\n    metadata:\n      labels:\n        app: ${m.deployment.metadata.name}\n    spec:\n      containers:\n        - name: ${m.deployment.spec.template.spec.containers[0].name}\n          image: ${m.deployment.spec.template.spec.containers[0].image}\n          ports:\n            - containerPort: ${m.deployment.spec.template.spec.containers[0].ports[0]?.containerPort || 80}\n`;
    if (m.deployment.spec.template.spec.containers[0].env.length > 0) {
      output += `          env:\n`;
      for (const e of m.deployment.spec.template.spec.containers[0].env) {
        output += `            - name: ${e.name}\n              value: "${e.value}"\n`;
      }
    }
    output += `\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: ${m.service.metadata.name}\n  namespace: ${namespace}\nspec:\n  selector:\n    app: ${m.service.metadata.name}\n  ports:\n    - port: ${m.service.spec.ports[0]?.port || 80}\n      targetPort: ${m.service.spec.ports[0]?.targetPort || 80}\n  type: ClusterIP\n\n`;
  }

  return output;
}

function generateCI(provider, deployDesc, stages) {
  const stageList = stages ? stages.split(',').map(s => s.trim()) : ['test', 'build', 'deploy'];

  if (provider === 'github-actions') {
    let yml = `name: CI/CD Pipeline\n\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n`;
    for (const stage of stageList) {
      yml += `  ${stage}:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n`;
      if (stage === 'test') {
        yml += `      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm ci\n      - run: npm test\n`;
      } else if (stage === 'build') {
        yml += `      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm ci\n      - run: npm run build\n`;
      } else if (stage === 'deploy') {
        yml += `      - run: echo "Deploy step"\n`;
        if (deployDesc) yml += `        # ${deployDesc}\n`;
      }
      yml += '\n';
    }
    return yml;
  }

  if (provider === 'gitlab') {
    let yml = `stages:\n`;
    for (const s of stageList) yml += `  - ${s}\n`;
    yml += '\n';
    for (const stage of stageList) {
      yml += `${stage}:\n  stage: ${stage}\n  script:\n`;
      if (stage === 'test') yml += `    - npm ci\n    - npm test\n`;
      else if (stage === 'build') yml += `    - npm ci\n    - npm run build\n`;
      else yml += `    - echo "Deploy"\n`;
      yml += '\n';
    }
    return yml;
  }

  if (provider === 'circleci') {
    let yml = `version: 2.1\n\njobs:\n`;
    for (const stage of stageList) {
      yml += `  ${stage}:\n    docker:\n      - image: cimg/node:20.0\n    steps:\n      - checkout\n`;
      if (stage === 'test') yml += `      - run: npm ci\n      - run: npm test\n`;
      else if (stage === 'build') yml += `      - run: npm ci\n      - run: npm run build\n`;
      else yml += `      - run: echo "Deploy"\n`;
      yml += '\n';
    }
    yml += `\nworkflows:\n  main:\n    jobs:\n`;
    for (const s of stageList) yml += `      - ${s}\n`;
    return yml;
  }

  if (provider === 'bitbucket') {
    let yml = `pipelines:\n  default:\n    - step:\n        name: ${stageList[0]}\n        image: node:20\n        script:\n          - npm ci\n          - npm test\n`;
    for (const stage of stageList.slice(1)) {
      yml += `    - step:\n        name: ${stage}\n        image: node:20\n        script:\n`;
      if (stage === 'build') yml += `          - npm run build\n`;
      else yml += `          - echo "Deploy"\n`;
    }
    return yml;
  }

  return `# Unsupported provider: ${provider}`;
}

function generateNginx(description) {
  const rules = description.split(',').map(r => r.trim());
  let config = `# Generated by skillpack infra-gen\n# ${description}\n\nserver {\n    listen 80;\n    server_name _;\n\n`;

  for (const rule of rules) {
    const proxyMatch = rule.match(/proxy\s+(\S+)\s+to\s+(\S+)/i);
    const staticMatch = rule.match(/serve\s+(\S+)\s+from\s+(\S+)/i);

    if (proxyMatch) {
      const [, from, to] = proxyMatch;
      config += `    location ${from} {\n        proxy_pass ${to};\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n    }\n\n`;
    } else if (staticMatch) {
      const [, path, root] = staticMatch;
      config += `    location ${path} {\n        root ${root};\n        try_files $uri $uri/ =404;\n    }\n\n`;
    }
  }

  config += `}\n`;
  return config;
}

function generateApache(description) {
  const rules = description.split(',').map(r => r.trim());
  let config = `# Generated by skillpack infra-gen\n# ${description}\n\n<VirtualHost *:80>\n    ServerName _\n\n    ProxyPreserveHost On\n`;

  for (const rule of rules) {
    const proxyMatch = rule.match(/proxy\s+(\S+)\s+to\s+(\S+)/i);
    if (proxyMatch) {
      const [, from, to] = proxyMatch;
      config += `    ProxyPass ${from} ${to}\n    ProxyPassReverse ${from} ${to}\n`;
    }
  }

  config += `\n    ErrorLog \${APACHE_LOG_DIR}/error.log\n    CustomLog \${APACHE_LOG_DIR}/access.log combined\n</VirtualHost>\n`;
  return config;
}

function generateTerraform(description) {
  const resources = [];
  const desc = description.toLowerCase();

  if (desc.includes('vpc')) {
    resources.push(`resource "aws_vpc" "main" {\n  cidr_block = "10.0.0.0/16"\n\n  tags = {\n    Name = "main-vpc"\n  }\n}\n\nresource "aws_subnet" "public" {\n  vpc_id     = aws_vpc.main.id\n  cidr_block = "10.0.1.0/24"\n\n  tags = {\n    Name = "public-subnet"\n  }\n}`);
  }

  if (desc.includes('ecs') || desc.includes('cluster')) {
    resources.push(`resource "aws_ecs_cluster" "main" {\n  name = "main-cluster"\n\n  setting {\n    name  = "containerInsights"\n    value = "enabled"\n  }\n}`);
  }

  if (desc.includes('rds') || desc.includes('postgres') || desc.includes('database')) {
    resources.push(`resource "aws_db_instance" "main" {\n  identifier     = "main-db"\n  engine         = "postgres"\n  engine_version = "15"\n  instance_class = "db.t3.micro"\n  allocated_storage = 20\n\n  db_name  = "app"\n  username = var.db_username\n  password = var.db_password\n\n  skip_final_snapshot = true\n}`);
  }

  if (desc.includes('s3') || desc.includes('bucket')) {
    resources.push(`resource "aws_s3_bucket" "main" {\n  bucket = "my-app-bucket"\n\n  tags = {\n    Name = "Main bucket"\n  }\n}\n\nresource "aws_s3_bucket_versioning" "main" {\n  bucket = aws_s3_bucket.main.id\n\n  versioning_configuration {\n    status = "Enabled"\n  }\n}`);
  }

  if (resources.length === 0) {
    resources.push(`# No resources detected from description: ${description}`);
  }

  return `# Generated by skillpack infra-gen\n# ${description}\n\nterraform {\n  required_providers {\n    aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.0"\n    }\n  }\n}\n\nprovider "aws" {\n  region = "us-east-1"\n}\n\nvariable "db_username" {\n  type = string\n  sensitive = true\n}\n\nvariable "db_password" {\n  type = string\n  sensitive = true\n}\n\n${resources.join('\n\n')}\n`;
}

function writeOutput(content, args, filename) {
  if (args.dryRun) {
    process.stderr.write('[dry-run] Would write output:\n');
    process.stdout.write(content);
    return;
  }
  if (args.out) {
    fs.mkdirSync(args.out, { recursive: true });
    const outPath = path.join(args.out, filename);
    fs.writeFileSync(outPath, content);
    process.stderr.write(`Written to ${outPath}\n`);
  } else {
    process.stdout.write(content);
  }
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) { printHelp(); process.exit(0); }
  if (!args.subcommand) { printHelp(); process.exit(0); }

  switch (args.subcommand) {
    case 'k8s': {
      const file = args.files[0];
      if (!file || !fs.existsSync(file)) { console.error('Error: docker-compose file not found.'); process.exit(1); }
      const k8s = dockerToK8s(file, args.namespace);
      writeOutput(k8s, args, 'k8s-manifests.yml');
      break;
    }
    case 'ci': {
      const ci = generateCI(args.provider, args.deploy, args.stages);
      const filename = args.provider === 'github-actions' ? 'ci.yml' : args.provider === 'gitlab' ? '.gitlab-ci.yml' : args.provider === 'circleci' ? '.circleci/config.yml' : 'bitbucket-pipelines.yml';
      writeOutput(ci, args, filename);
      break;
    }
    case 'nginx': {
      const desc = args.files.join(' ') || 'proxy /api to localhost:3000';
      const config = generateNginx(desc);
      writeOutput(config, args, 'nginx.conf');
      break;
    }
    case 'apache': {
      const desc = args.files.join(' ') || 'proxy /api to localhost:3000';
      const config = generateApache(desc);
      writeOutput(config, args, 'apache.conf');
      break;
    }
    case 'terraform': {
      const desc = args.files.join(' ') || 'AWS VPC with public subnet';
      const tf = generateTerraform(desc);
      writeOutput(tf, args, 'main.tf');
      break;
    }
    default:
      console.error(`Error: Unknown subcommand "${args.subcommand}"`);
      process.exit(1);
  }
}

main();
